### ISSUE TITLE
help

### ISSUE THREAD

**Issue by lxstudying** [CoderWanp/neo4j-d3-graph#2]
题主你好，按照你的路径配置了自己的数据修改了代码，可是网页没有出现节点和关系，还有启动服务是啥意思啊，小白一个，万望解答
![image](https://user-images.githubusercontent.com/73649745/133880548-f3348eb9-e24d-4c73-a35a-e43c3b5940cd.png)

**Comment by learninghard1** [comment]
我也有这个问题 请问您怎么解决的呢

**Comment by lxstudying** [comment]
> 我也有这个问题 请问您怎么解决的呢

数据量搞小一点。。。。

**Comment by learninghard1** [comment]
呃 您好 我也小白一个刚开始学这方面的内容 那个启动服务什么意思啊 我也没太搞懂 可以加一下联系方式什么的吗

**Comment by learninghard1** [comment]
或者您能帮忙解释一下这个程序是如何操作的也行……

**Comment by lxstudying** [comment]
> 呃 您好 我也小白一个刚开始学这方面的内容 那个启动服务什么意思啊 我也没太搞懂 可以加一下联系方式什么的吗

qq527301865,我也想有人交流下

**Comment by DW934** [comment]
pycharm中启动服务的意思就是在pycharm中打开index.html，右上角会有提示你选择一种浏览方式，你选择浏览器（edge）就可以在浏览器里看到网页了
