### ISSUE TITLE
help

### ISSUE THREAD

**Issue by lxstudying** [CoderWanp/neo4j-d3-graph#3]
![image](https://user-images.githubusercontent.com/73649745/133882334-56e670b2-f170-4fe9-b5b2-29bb268947ad.png)
你好，我按照你的路径配置了我的数据，但页面没有节点与关系出现
![image](https://user-images.githubusercontent.com/73649745/133882406-54e3ea6c-69cb-430e-ba3f-d20c437c82d9.png)

**Comment by lxstudying** [comment]
> ![图片](https://user-images.githubusercontent.com/73649745/133882334-56e670b2-f170-4fe9-b5b2-29bb268947ad.png)
> 你好，我按照你的路径配置了我的数据，但页面没有节点与关系出现
> ![图片](https://user-images.githubusercontent.com/73649745/133882406-54e3ea6c-69cb-430e-ba3f-d20c437c82d9.png)

**Comment by learninghard1** [comment]
您好 请问您是怎么解决的呢

**Comment by learninghard1** [comment]
我也有这个问题
