### ISSUE TITLE
数据过大时，节点关系不显示

### ISSUE THREAD

**Issue by lxstudying** [CoderWanp/neo4j-d3-graph#4]
![image](https://user-images.githubusercontent.com/73649745/134448916-1b12393d-999b-4f97-a560-8219371ac823.png)
1、从neo4j中导出部分关系节点，可以显示
2、但当我的json文件大小为18m时，网页只出现了图例等，无节点出现
3、请问我改怎么修改，以可视化我的图谱
谢谢！

**Comment by CoderWanp** [comment]
18m的数据量太大了，我这种可视化方法是做不到的，你可以尝试使用canvas来渲染，同时需要从数据和绘制两个方面来简化你的图谱
